to_do_list/app_modules/base/urls.py
from django.urls import path

urlpatterns = [
    # path('login/',),
]

to_do_list/app_modules/tasks/urls.py
from django.urls import path
from app_modules.tasks import views

app_name = "tasks"

urlpatterns = [
    path('', views.ListTaskView.as_view(), name="list_task"),
    path('create/', views.CreateTaskView.as_view(), name="create_task"),
    path('update/<int:pk>/', views.UpdateTaskView.as_view(), name="update_task"),
    path('delete/<int:pk>/', views.DeleteTaskView.as_view(), name="delete_task"),
]

to_do_list/app_modules/users/urls.py
from django.urls import path
from app_modules.users import views

app_name = "users"

urlpatterns = [
    path('', views.DashboardView.as_view(), name="dashboard"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('register/', views.RegisterView.as_view(), name="register"),
]

to_do_list/to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_modules.users.urls")),
    path('tasks/', include("app_modules.tasks.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_do_list/app_modules/base/models.py
from django.db import models

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    class Meta:
        abstract = True

to_do_list/app_modules/tasks/models.py
from django.db import models
from app_modules.base.models import BaseModel


class Task(BaseModel):
    PENDING = "pending"
    COMPLETED = "completed"

    STATUSES = (
        (PENDING, "Pending"),
        (COMPLETED, "Completed"),
    )

    title = models.CharField("Title", max_length=200)
    description = models.TextField("Description", null=True, blank=True)
    due_date = models.DateField("Due Date", null=True, blank=True)
    status = models.CharField("Status", choices=STATUSES, max_length=100, default=PENDING)

    def __str__(self):
        return self.title

    

to_do_list/app_modules/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from app_modules.base.models import BaseModel


class User(AbstractUser, BaseModel):
    ADMIN = "admin"
    EMPLOYEE = "employee"

    USER_ROLE = (
        (ADMIN, "Admin"),
        (EMPLOYEE, "Employee"),
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    email = models.EmailField(('Email'), unique=True)
    full_name = models.CharField(('Full Name'), max_length=50)
    image = models.FileField(upload_to='user-profile', null=True, blank=True)
    role = models.CharField(('Role'), choices=USER_ROLE, max_length=50, default=EMPLOYEE)

    def __str__(self):
        return self.full_name

to_do_list/app_modules/tasks/forms.py
from django import forms
from .models import Task

class CreateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ("title", "description", "due_date")
        widgets={
            'due_date' : forms.TextInput(attrs={'type':'date'})
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["placeholder"] = visible.field.label


class UpdateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"
        widgets={
            'due_date' : forms.TextInput(attrs={'type':'date'})
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["placeholder"] = visible.field.label

to_do_list/app_modules/users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "password")
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["placeholder"] = visible.field.label
        

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "full_name", "password1", "password2")
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            visible.field.widget.attrs["placeholder"] = visible.field.label

to_do_list/app_modules/base/views.py
from django.shortcuts import render

# Create your views here.

to_do_list/app_modules/tasks/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, ListView, View
from .forms import CreateTaskForm, UpdateTaskForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Task

from django.contrib.auth.mixins import LoginRequiredMixin


class ListTaskView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list-task.html"


class CreateTaskView(LoginRequiredMixin, CreateView):
    template_name = "tasks/create-task.html"
    form_class = CreateTaskForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse("tasks:list_task"))

    def form_invalid(self, form):
        return super().form_invalid(form)
    
    
class UpdateTaskView(LoginRequiredMixin, UpdateView):
    template_name = "tasks/update-task.html"
    form_class = UpdateTaskForm
    model = Task

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse("tasks:list_task"))

    def form_invalid(self, form):
        return super().form_invalid(form)


class DeleteTaskView(LoginRequiredMixin, View):
    def get(self, request, pk):
        Task.objects.filter(id = pk).delete()
        return HttpResponseRedirect(reverse("tasks:list_task"))

to_do_list/app_modules/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, View
from .forms import LoginForm, RegisterForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from app_modules.tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import get_user_model
User = get_user_model()


class LoginView(TemplateView):
    template_name = "users/login.html"
    form_class = LoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = LoginForm()
        return context

    def post(self, request):
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)

        if user is not None:
            login(self.request, user)
            return HttpResponseRedirect(reverse("users:dashboard"))
        return render(self.request, self.template_name, {"form": LoginForm(), "error": "Login credentials are incorrect !!!"})


class LogoutView(View):
    def get(self, request):
        logout(self.request)
        return HttpResponseRedirect(reverse("users:login"))


class RegisterView(CreateView):
    template_name = "users/register.html"
    form_class = RegisterForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse("users:login"))

    def form_invalid(self, form):
        return super().form_invalid(form)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "users/dashboard.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["object_list"] = Task.objects.all()
        return context

to_do_list/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %} | To Do</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
    
    {% block css %}{% endblock css %}
  </head>
  <body>

    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock navbar %}

    {% block body %}
    {% endblock body %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="main.js"></script>
    
    {% block js %}{% endblock js %}
        
  </body>
</html>

to_do_list/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:dashboard' %}">Home</a>
          </li>
          {% endif %}
        </ul>
        <div class="d-flex">
          
          {% if request.user.is_authenticated %}
            <a href="{% url 'users:logout' %}"><button class="btn btn-outline-success">Logout</button></a>
          {% else %}
            <a href="{% url 'users:login' %}"><button class="btn btn-outline-primary mx-2">Login</button></a>
            <a href="{% url 'users:register' %}"><button class="btn btn-primary mx-2">Register</button></a>
          {% endif %}
            
        </div>
      </div>
    </div>
</nav>

to_do_list/templates/tasks/create-task.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
</style>

{% endblock css %}

{% block body %}
<div class="d-flex align-items-center py-4 bg-body-tertiary mt-5">
<div class="form-signin w-50 m-auto">
    <form method="post" novalidate>
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Create Task</h1>

        <div class="form-floating">
            {{ form.title }}
            <label for="floatingInput">{{ form.title.label }}</label>
            {% if form.title.errors %}
                {% for error in form.title.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.description }}
            <label for="floatingInput">{{ form.description.label }}</label>
            {% if form.description.errors %}
                {% for error in form.description.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.due_date }}
            <label for="floatingPassword">{{ form.due_date.label }}</label>
            {% if form.due_date.errors %}
                {% for error in form.due_date.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>

        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Create</button>
    </form>
</div>
</div>
{% endblock body %}

to_do_list/templates/tasks/list-task.html
{% extends 'base.html' %}


{% block body %}
<div class="container py-4 bg-body-tertiary mt-5">
    <div class="d-flex justify-content-between">
        <h3>Tasks</h3>
        <a href="{% url 'tasks:create_task' %}"><button class="btn btn-primary">Create Task</button></a>
    </div>

    <table class="table">
        <thead>
            <th>ID</th>
            <th>Title</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Actions</th>
        </thead>
        <tbody>
            
            {% for task in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ task.title }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.status }}</td>
                <td>
                    <div class="d-flex justify-content-start">
                        <div>
                            <a href="{% url 'tasks:update_task' task.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001"/>
                                </svg>
                            </a>
                        </div>
                        <div class="mx-2 ">
                            <a href="{% url 'tasks:delete_task' task.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill text-danger" viewBox="0 0 16 16">
                                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock body %}
    

to_do_list/templates/tasks/update-task.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
</style>

{% endblock css %}

{% block body %}
<div class="d-flex align-items-center py-4 bg-body-tertiary mt-5">
<div class="form-signin w-50 m-auto">
    <form method="post" novalidate>
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Create Task</h1>

        <div class="form-floating">
            {{ form.title }}
            <label for="floatingInput">{{ form.title.label }}</label>
            {% if form.title.errors %}
                {% for error in form.title.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.description }}
            <label for="floatingInput">{{ form.description.label }}</label>
            {% if form.description.errors %}
                {% for error in form.description.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.due_date }}
            <label for="floatingPassword">{{ form.due_date.label }}</label>
            {% if form.due_date.errors %}
                {% for error in form.due_date.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.status }}
          <label for="floatingPassword">{{ form.status.label }}</label>
          {% if form.status.errors %}
              {% for error in form.status.errors %}
              <p style="color: red;">{{error}}</p>
              {% endfor %}
          {% endif %}
      </div>

        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Update</button>
    </form>
</div>
</div>
{% endblock body %}

to_do_list/templates/users/dashboard.html
{% include 'tasks/list-task.html' %}

to_do_list/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
  </style>

  <link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock css %}

{% block body %}
<div class="d-flex align-items-center py-4 bg-body-tertiary mt-5">
<div class="form-signin w-50 m-auto">
    <form method="post" novalidate>
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Log in</h1>

        <div class="form-floating">
            {{ form.email }}
            <label for="floatingInput">{{ form.email.label }}</label>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.password }}
            <label for="floatingPassword">{{ form.password.label }}</label>
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>

        <div class="text-danger">{{ error }}</div>

        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Log in</button>
    </form>
</div>
</div>
{% endblock body %}

to_do_list/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
</style>

<link rel="stylesheet" href="{% static 'login.css' %}">
{% endblock css %}

{% block body %}
<div class="d-flex align-items-center py-4 bg-body-tertiary mt-5">
<div class="form-signin w-50 m-auto">
    <form method="post" novalidate>
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Register</h1>

        <div class="form-floating">
            {{ form.full_name }}
            <label for="floatingInput">{{ form.full_name.label }}</label>
            {% if form.full_name.errors %}
                {% for error in form.full_name.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.email }}
            <label for="floatingInput">{{ form.email.label }}</label>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.password1 }}
            <label for="floatingPassword">{{ form.password1.label }}</label>
            {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
            {{ form.password2 }}
            <label for="floatingPassword">{{ form.password2.label }}</label>
            {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>

        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Register</button>
    </form>
</div>
</div>
{% endblock body %}